### ISSUE TITLE
Causes an Internal Server Error

### ISSUE THREAD

**Issue by Kevin-Oudai** [Kevin-Oudai/django-mcquiz#1]
When the quiz is submitted without any answers the following error is obtained
`
2021-10-18 23:24:15,416: Internal Server Error: /quiz/1/quiz-number-1/solutions
Traceback (most recent call last):
  File "/home/MrOudai/.virtualenvs/mroudai-env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/MrOudai/.virtualenvs/mroudai-env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/MrOudai/.virtualenvs/mroudai-env/lib/python3.7/site-packages/MCQuizApp/views.py", line 56, in solutions
    correct_answers = [x.get_answer_id() for x in questions]
  File "/home/MrOudai/.virtualenvs/mroudai-env/lib/python3.7/site-packages/MCQuizApp/views.py", line 56, in <listcomp>
    correct_answers = [x.get_answer_id() for x in questions]
  File "/home/MrOudai/.virtualenvs/mroudai-env/lib/python3.7/site-packages/MCQuizApp/models.py", line 83, in get_answer_id
    question=self, correct=True).values('id')[0]['id'])
  File "/home/MrOudai/.virtualenvs/mroudai-env/lib/python3.7/site-packages/django/db/models/query.py", line 318, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
`

**Comment by Kevin-Oudai** [comment]
The view was not using the correct function to get the questions from the database.
